[package]
name = "paxos-classic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-new = "0.6.0"
futures = "0.3.30"
getset = "0.1.2"
thiserror = "1.0.53"
tracing = "0.1.40"
